### ISSUE TITLE
I want to add localization to Brazillian Portuguese

### ISSUE THREAD

**Issue by igorteuri** [apollo-fyi/apollo-docs#17]
Hello there!

I loved your bot, and I use it a lot in my server to plan tabletop RPG games, even though I only use the free version. 
I wanted to add localization to brazillian portuguese. Is it possible?

**Comment by jgayfer** [comment]
Hello! We have our translations here: https://crowdin.com/project/apollo-discord-bot

We have decent progress on Brazilian Portuguese already. More help would certainly be appreciated.
