### ISSUE TITLE
Last Commit Added Threaded Reminders... Removed DM Reminder Option... Why not both?

### ISSUE THREAD

**Issue by git-you-cat** [apollo-fyi/apollo-docs#6]
Our server hates threads.
DM reminders worked very well for us.
Why not have both options?
(Of course the people getting DM reminders have to accept DMs from server. That is a pre-req unless Apollo-bot can auto-accept friends...)

**Comment by reiichi001** [comment]
Hi @mochizuki-8, the documentation site's source is not the best place to provide feedback for Apollo.

We have a dedicated feedback section on Apollo's Discord server and feedback can also be submitted on https://feedback.apollo.fyi/ 

The change to reminder messages (in or out of threads) was also noted in our announcements channel.

> We’ve transitioned event reminders from DMs to threads. Rather than sending potentially hundreds of reminder messages, we now send a single message per event that mentions relevant attendees. If you’d prefer Apollo to not create threads, Apollo can be configured to send reminders in the event channel instead with `!server thread_reminders off`.
> 
> We’ve also added a way to have Apollo create a thread for all new posted events. The command to enable this is `!server event_threads on`.
> 
> I recognize that some of you quite liked DM reminders, but ultimately they had to go for performance reasons. If you’ve ever noticed slowdown from Apollo, that’s often because we’re processing hundreds (or thousands) of individual reminder messages. The new system is much more performant under load, and is more transparent as to how and when reminders are delivered. Thank you for understanding.
